---
# app-in-logical-env chart to use to generate application within one logical env
appLogicalEnvChart:
  repoURL: https://dnv-gssit.github.io/kubeit-charts
  chart: kubeit-apps-in-env
  targetRevision: 1.0.5
